dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules

before_script:
  - npm install -g truffle
script:
  # - npm run lint:sol
  - npm run test